version: '3'

services:
    nginx:
        build: infra/nginx
        ports:
            - "80:80"
        depends_on:
            - php-fpm
            - database

    php-fpm:
        build:
            dockerfile: infra/php/Dockerfile
            context: .

    database:
        build: infra/mariadb
        restart: always
        volumes:
            - ./infra/mariadb/data:/var/lib/mysql
        ports:
            - "3306:3306"
